export const URL = 'https://rifadasorte.herokuapp.com/'
export const get_draws = 'draw/'
export const get_numbers = 'draw/numbers/'
export const post_register = 'draw/auth/'
export const endpoint_get_token = 'api/token/'
export const endpoint_refresh_token = 'api/token/refresh/'
export const set_request = 'draw/request/'